"""create_table_CentralCoast

Revision ID: 45e45da8fcec
Revises: f4238638ee00
Create Date: 2024-04-24 17:27:20.745295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45e45da8fcec'
down_revision: Union[str, None] = 'f4238638ee00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweed_shire_council',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('app_num', sa.String(length=500), nullable=False),
    sa.Column('detail_text', sa.Text(), nullable=True),
    sa.Column('detail_Lodged_data', sa.Integer(), nullable=True),
    sa.Column('detail_Determined_data', sa.String(length=255), nullable=True),
    sa.Column('detail_cost', sa.String(length=255), nullable=True),
    sa.Column('detail_officer', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('people_Applicant', sa.String(length=255), nullable=True),
    sa.Column('documents_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id'),
    sa.UniqueConstraint('app_num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wollongong',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_number', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('ApplicationType', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('SiteName', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('Description', mysql.TEXT(), nullable=True),
    sa.Column('Lodged', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Accepted', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Determined', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('Effective', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ModificationCategory', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('development', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('NSWPlanningPortal', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('notification', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('dwellinghouse', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('Lapsed', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Completed', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('progress', mysql.TEXT(), nullable=True),
    sa.Column('people', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('associations', mysql.TEXT(), nullable=True),
    sa.Column('documents', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('app_number', 'wollongong', ['app_number'], unique=True)
    op.drop_table('tweed_shire_council')
    # ### end Alembic commands ###
