"""create_table_CentralCoast

Revision ID: 76f9b2ba2523
Revises: d377da8bc2c3
Create Date: 2024-04-24 11:58:50.421277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '76f9b2ba2523'
down_revision: Union[str, None] = 'd377da8bc2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercialrealestate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_number', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_', sa.String(length=255), nullable=True),
    sa.Column('floor_area', sa.String(length=255), nullable=True),
    sa.Column('land_area', sa.String(length=255), nullable=True),
    sa.Column('parking', sa.String(length=255), nullable=True),
    sa.Column('annual_return', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('agent_info', sa.Text(), nullable=True),
    sa.Column('closing_date', sa.Integer(), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kingborough',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_num', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('app_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('advertised_date', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('closing_date', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purpose', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('documents', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('app_num', 'kingborough', ['app_num'], unique=True)
    op.create_table('kwinana',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', mysql.VARCHAR(length=126), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('key_dates', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('documents', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('application_id', 'kwinana', ['application_id'], unique=True)
    op.drop_table('commercialrealestate')
    # ### end Alembic commands ###
