"""create_table_CentralCoast

Revision ID: f4238638ee00
Revises: 76f9b2ba2523
Create Date: 2024-04-24 17:13:02.876136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f4238638ee00'
down_revision: Union[str, None] = '76f9b2ba2523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wollongong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_number', sa.String(length=128), nullable=False),
    sa.Column('ApplicationType', sa.String(length=512), nullable=True),
    sa.Column('SiteName', sa.String(length=512), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Lodged', sa.Integer(), nullable=True),
    sa.Column('Accepted', sa.Integer(), nullable=True),
    sa.Column('Determined', sa.String(length=512), nullable=True),
    sa.Column('Effective', sa.Integer(), nullable=True),
    sa.Column('ModificationCategory', sa.String(length=512), nullable=True),
    sa.Column('development', sa.String(length=512), nullable=True),
    sa.Column('NSWPlanningPortal', sa.String(length=512), nullable=True),
    sa.Column('notification', sa.String(length=512), nullable=True),
    sa.Column('dwellinghouse', sa.String(length=512), nullable=True),
    sa.Column('Lapsed', sa.Integer(), nullable=True),
    sa.Column('Completed', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Text(), nullable=True),
    sa.Column('people', sa.String(length=512), nullable=True),
    sa.Column('associations', sa.Text(), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_number')
    )
    op.drop_index('application_id', table_name='kwinana')
    op.drop_table('kwinana')
    op.drop_index('app_number', table_name='kalamunda')
    op.drop_table('kalamunda')
    op.drop_index('app_num', table_name='kingborough')
    op.drop_table('kingborough')
    op.drop_index('app_number', table_name='commercialrealestate')
    op.drop_table('commercialrealestate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercialrealestate',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('type_', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('floor_area', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('land_area', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('parking', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('annual_return', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('availability', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('value', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('agent_info', mysql.TEXT(), nullable=True),
    sa.Column('closing_date', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('delivery_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('app_number', 'commercialrealestate', ['app_number'], unique=True)
    op.create_table('kingborough',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_num', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('app_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('advertised_date', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('closing_date', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purpose', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('documents', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('app_num', 'kingborough', ['app_num'], unique=True)
    op.create_table('kalamunda',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('app_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('lodgement_date', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('applicant', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telephone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.TEXT(), nullable=True),
    sa.Column('decision', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('decision_date', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stage_', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('start_date', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('end_date', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('app_number', 'kalamunda', ['app_number'], unique=True)
    op.create_table('kwinana',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', mysql.VARCHAR(length=126), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('key_dates', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('documents', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('application_id', 'kwinana', ['application_id'], unique=True)
    op.drop_table('wollongong')
    # ### end Alembic commands ###
